[Reference](https://towardsdatascience.com/what-are-lambda-functions-in-python-and-why-you-should-start-using-them-right-now-75ab85655dc6)

In [1]:
my_list = [1, 2, 3, 4, 5]
list(filter(lambda x: x > 2, my_list))

[3, 4, 5]

In [2]:
from sklearn import datasets
import pandas as pd
iris_data = datasets.load_iris()
df_iris = pd.DataFrame(iris_data.data,columns=iris_data.feature_names)
df_iris['target'] = pd.Series(iris_data.target)
df_iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [3]:
df_iris['sepal_length_description'] = df_iris['sepal length (cm)'].apply(lambda x: 'sepal length is: ' + str(x))
df_iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,sepal_length_description
0,5.1,3.5,1.4,0.2,0,sepal length is: 5.1
1,4.9,3.0,1.4,0.2,0,sepal length is: 4.9
2,4.7,3.2,1.3,0.2,0,sepal length is: 4.7
3,4.6,3.1,1.5,0.2,0,sepal length is: 4.6
4,5.0,3.6,1.4,0.2,0,sepal length is: 5.0

In [4]:
df_iris['sepal_description'] = df_iris.apply(lambda x: 'sepal length/width ration is :' + str(round(x['sepal length (cm)'] / x['sepal width (cm)'], 2)), axis=1)
df_iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,sepal_length_description,sepal_description
0,5.1,3.5,1.4,0.2,0,sepal length is: 5.1,sepal length/width ration is :1.46
1,4.9,3.0,1.4,0.2,0,sepal length is: 4.9,sepal length/width ration is :1.63
2,4.7,3.2,1.3,0.2,0,sepal length is: 4.7,sepal length/width ration is :1.47
3,4.6,3.1,1.5,0.2,0,sepal length is: 4.6,sepal length/width ration is :1.48
4,5.0,3.6,1.4,0.2,0,sepal length is: 5.0,sepal length/width ration is :1.39