[Reference](https://anmol3015.medium.com/8-use-cases-of-most-powerful-python-functions-apply-and-lambda-8e2d03e3e175)

In [1]:
lambda x: x*2

In [2]:
import pandas as pd
add_10 = lambda x: x+10
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df.apply(add_10)

    A   B
0  11  14
1  12  15
2  13  16

In [3]:
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
max_value = lambda x: x.max()
df.apply(max_value, axis=1)
df.apply(max_value, axis=0)

A    3
B    6
dtype: int64

In [4]:
range = lambda x: x.max() - x.min()
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df.apply(range)

A    2
B    2
dtype: int64

In [5]:
to_lower= lambda x: x.str.lower() if isinstance(x, object) else x
df = pd.DataFrame({'A':['A','B','C'],'B':['X','Y','Z']})
df.apply(to_lower)

   A  B
0  a  x
1  b  y
2  c  z

In [6]:
normalize = lambda x: (x - x.mean()) / x.std()
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df.apply(normalize)

     A    B
0 -1.0 -1.0
1  0.0  0.0
2  1.0  1.0

In [7]:
replace_missing = lambda x, value: x.fillna(value)
df = pd.DataFrame({'A':[1,2,None],'B':[None,5,6]})
df.apply(replace_missing, args=(0,))

     A    B
0  1.0  0.0
1  2.0  5.0
2  0.0  6.0

In [8]:
cumsum = lambda x: x.cumsum()
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df.apply(cumsum)

   A   B
0  1   4
1  3   9
2  6  15

In [9]:
moving_average = lambda x: x.rolling(window=2).mean()
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df.apply(moving_average)

     A    B
0  NaN  NaN
1  1.5  4.5
2  2.5  5.5