[Reference](https://medium.com/@anala007/how-to-use-python-pandas-shift-function-6b0e017e8ee7)

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"Col1": [10, 20, 15, 30, 45],"Col2": [13, 23, 18, 33, 48],"Col3": [17, 27, 22, 37, 52]},index=pd.date_range("2022-01-01", "2022-01-05"))
df

            Col1  Col2  Col3
2022-01-01    10    13    17
2022-01-02    20    23    27
2022-01-03    15    18    22
2022-01-04    30    33    37
2022-01-05    45    48    52

In [3]:
df.shift(periods=1)

            Col1  Col2  Col3
2022-01-01   NaN   NaN   NaN
2022-01-02  10.0  13.0  17.0
2022-01-03  20.0  23.0  27.0
2022-01-04  15.0  18.0  22.0
2022-01-05  30.0  33.0  37.0

In [4]:
df.shift(periods=2, freq='D')

            Col1  Col2  Col3
2022-01-03    10    13    17
2022-01-04    20    23    27
2022-01-05    15    18    22
2022-01-06    30    33    37
2022-01-07    45    48    52

In [5]:
df.shift(periods=3, fill_value=0)

            Col1  Col2  Col3
2022-01-01     0     0     0
2022-01-02     0     0     0
2022-01-03     0     0     0
2022-01-04    10    13    17
2022-01-05    20    23    27