[Reference](https://medium.com/swlh/how-to-scrape-a-website-with-a-single-line-of-python-code-5efe124275bb)

In [5]:
import pandas as pd
data = pd.read_html('https://en.wikipedia.org/wiki/Super_Bowl_LIV')

In [6]:
print(len(data))

25

In [7]:
data[6]

                           Statistic San Francisco 49ers Kansas City Chiefs
0                        First downs                  21                 26
1                First downs rushing                   8                 12
2                First downs passing                  13                 13
3                First downs penalty                   0                  1
4              Third down efficiency                 3/8               6/14
5             Fourth down efficiency                 0/1                2/3
6                    Total net yards                 351                397
7                  Net yards rushing                 141                129
8                   Rushing attempts                  22                 29
9                     Yards per rush                 6.4                4.4
10                     Yards passing                 210                286
11      Passing–completions/attempts               20/31              26/42
12          Times sacked–total yards                 1–9               4–18
13              Interceptions thrown                   2                  2
14          Punt returns–total yards                 1–0                0–0
15       Kickoff returns–total yards                4–61               3–58
16  Interceptions–total return yards                2–10               2–11
17             Punts–average yardage                2–43               2–40
18                      Fumbles–lost                 1–0                3–0
19                   Penalties–yards                5–45               4–24
20                Time of possession               26:47              33:13
21                         Turnovers                   2                  2

In [8]:
data[4]

                                      Scoring summary  ... Unnamed: 8
0   Quarter Time Drive Team Scoring information Sc...  ...        NaN
1                                             Quarter  ...      Score
2                                             Quarter  ...         KC
3                                                   1  ...          0
4                                                   1  ...          7
5                                                   2  ...         10
6                                                   2  ...         10
7                                                   3  ...         10
8                                                   3  ...         10
9                                                   4  ...         17
10                                                  4  ...         24
11                                                  4  ...         31
12  "TOP" = time of possession. For other American...  ...         31

[13 rows x 9 columns]

In [10]:
df = data[4]
df = df.drop([0, 1, 12], axis=0)
df

   Scoring summary Unnamed: 1  ... Unnamed: 7 Unnamed: 8
2          Quarter       Time  ...         SF         KC
3                1       7:57  ...          3          0
4                1       0:31  ...          3          7
5                2       9:32  ...          3         10
6                2       5:05  ...         10         10
7                3       9:29  ...         13         10
8                3       2:35  ...         20         10
9                4       6:13  ...         20         17
10               4       2:44  ...         20         24
11               4       1:12  ...         20         31

[10 rows x 9 columns]

In [11]:
df.iloc[0]

Scoring summary                Quarter
Unnamed: 1                        Time
Unnamed: 2                       Plays
Unnamed: 3                       Yards
Unnamed: 4                         TOP
Unnamed: 5                        Team
Unnamed: 6         Scoring information
Unnamed: 7                          SF
Unnamed: 8                          KC
Name: 2, dtype: object

In [12]:
df.columns = list(df.iloc[0])
df

    Quarter  Time  ...  SF  KC
2   Quarter  Time  ...  SF  KC
3         1  7:57  ...   3   0
4         1  0:31  ...   3   7
5         2  9:32  ...   3  10
6         2  5:05  ...  10  10
7         3  9:29  ...  13  10
8         3  2:35  ...  20  10
9         4  6:13  ...  20  17
10        4  2:44  ...  20  24
11        4  1:12  ...  20  31

[10 rows x 9 columns]

In [13]:
df = df.drop(2, axis=0)
df

   Quarter  Time  ...  SF  KC
3        1  7:57  ...   3   0
4        1  0:31  ...   3   7
5        2  9:32  ...   3  10
6        2  5:05  ...  10  10
7        3  9:29  ...  13  10
8        3  2:35  ...  20  10
9        4  6:13  ...  20  17
10       4  2:44  ...  20  24
11       4  1:12  ...  20  31

[9 rows x 9 columns]

In [14]:
df = df.reset_index(drop=True)
df

  Quarter  Time  ...  SF  KC
0       1  7:57  ...   3   0
1       1  0:31  ...   3   7
2       2  9:32  ...   3  10
3       2  5:05  ...  10  10
4       3  9:29  ...  13  10
5       3  2:35  ...  20  10
6       4  6:13  ...  20  17
7       4  2:44  ...  20  24
8       4  1:12  ...  20  31

[9 rows x 9 columns]

In [17]:
def score_table(table):
 '''
 Returns a pretty-printed dataframe of scoring summary.
 '''
 table = table.drop(len(table)-1) # Drop last row
 table = table.drop([0, 1]) # Drop first two rows
 table.columns = list(table.iloc[0])
 table = table.drop(2) 
 table = table.reset_index(drop=True)  
 
 return table

In [18]:
data = pd.read_html('https://en.wikipedia.org/wiki/Super_Bowl_LIII')
score_table(data[4])

  Quarter   Time  ...  NE LAR
0       2  10:29  ...   3   0
1       3   2:11  ...   3   3
2       4   7:00  ...  10   3
3       4   1:12  ...  13   3

[4 rows x 9 columns]