[Reference](https://levelup.gitconnected.com/how-to-extract-tables-from-pdf-to-excel-in-python-538109b1bc0c)

In [1]:
!pip install tabula-py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tabula-py
  Downloading tabula_py-2.4.0-py3-none-any.whl (12.0 MB)
     |████████████████████████████████| 12.0 MB 17.5 MB/s
Collecting distro
  Downloading distro-1.7.0-py3-none-any.whl (20 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.21.6)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Installing collected packages: distro, tabula-py
Successfully installed distro-1.7.0 tabula-py-2.4.0

In [2]:
import tabula
import warnings
import plotly.express as px
from datetime import datetime
from google.colab import drive, files, output # specific to Google Colab

warnings.filterwarnings('ignore')

In [3]:
# Mean Sales Price of Existing Homes
url1 = "https://cdn.nar.realtor/sites/default/files/documents/ehs-06-2022-average-price-2022-07-21.pdf"
table = tabula.read_pdf(url1, pages=1)
table[0]

   Year/Month U.S. Mean Price
0        2020         395,600
1        2021         462,400
2         NaN             NaN
3     2020.01         352,700
4     2020.02         355,100
5     2020.03         369,200
6     2020.04         371,900
7     2020.05         367,500
8     2020.06         387,000
9     2020.07         402,300
10    2020.08         414,200
11    2020.09         415,800
12    2020.10         418,300
13    2020.11         415,300
14    2020.12         415,100
15    2021.01         408,600
16    2021.02         420,000
17    2021.03         441,700
18    2021.04         465,300
19    2021.05         475,300
20    2021.06         488,300
21    2021.07         480,800
22    2021.08         472,200
23    2021.09         462,700
24    2021.10         462,300
25    2021.11         464,600
26    2021.12         466,700
27    2022.01         458,900
28    2022.02         471,900
29    2022.03         501,400
30    2022.04         520,600
31    2022.05         532,300
32  2022.06 p         536,200

In [4]:
# normalize data
df_mean_sales_price = table[0]
df_mean_sales_price = df_mean_sales_price.iloc[3:,] # select month data
df_mean_sales_price['U.S. Mean Price'] = df_mean_sales_price.apply(lambda x: int(x['U.S. Mean Price'].replace(',', '')), axis=1)
df_mean_sales_price['Year/Month'] = df_mean_sales_price.apply(lambda x: x['Year/Month'][:7], axis=1)
df_mean_sales_price['Year/Month'] = df_mean_sales_price.apply(lambda x: datetime.strptime(x['Year/Month'], '%Y.%m'), axis=1)
df_mean_sales_price.tail(5)

   Year/Month  U.S. Mean Price
28 2022-02-01           471900
29 2022-03-01           501400
30 2022-04-01           520600
31 2022-05-01           532300
32 2022-06-01           536200

In [5]:
# uncomment below to download file
df_mean_sales_price.to_csv('output.csv', index=False)
files.download('output.csv')

In [6]:
# visualize data
fig = px.line(df_mean_sales_price, x="Year/Month", y="U.S. Mean Price", title='National Single Family Mean Price MoM')
fig.show()

In [7]:
# Pending Home Sales Index (PHSI)
url2 = "https://cdn.nar.realtor/sites/default/files/documents/phs-05-2022-pending-home-sales-06-27-2022.pdf"
table = tabula.read_pdf(url2, pages=1)

HTTPError: ignored

In [8]:
df_pending = table[0]
df_pending

   Year/Month U.S. Mean Price
0        2020         395,600
1        2021         462,400
2         NaN             NaN
3     2020.01         352,700
4     2020.02         355,100
5     2020.03         369,200
6     2020.04         371,900
7     2020.05         367,500
8     2020.06         387,000
9     2020.07         402,300
10    2020.08         414,200
11    2020.09         415,800
12    2020.10         418,300
13    2020.11         415,300
14    2020.12         415,100
15    2021.01         408,600
16    2021.02         420,000
17    2021.03         441,700
18    2021.04         465,300
19    2021.05         475,300
20    2021.06         488,300
21    2021.07         480,800
22    2021.08         472,200
23    2021.09         462,700
24    2021.10         462,300
25    2021.11         464,600
26    2021.12         466,700
27    2022.01         458,900
28    2022.02         471,900
29    2022.03         501,400
30    2022.04         520,600
31    2022.05         532,300
32  2022.06 p         536,200