[Reference](https://medium.com/@ayeshasidhikha188/iterating-over-rows-and-columns-in-pandas-dataframe-1027e8c99928)

In [1]:
import pandas as pd

In [2]:
dict_ = {'name': ["Ameena",'Muskan',"Needha","Sanvi"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score': [90, 40, 80, 98]}
df = pd.DataFrame(dict_)
df

     name  degree  score
0  Ameena     MBA     90
1  Muskan     BCA     40
2  Needha  M.Tech     80
3   Sanvi     MBA     98

In [3]:
# iterating over rows using iterrows() function
for i, j in df.iterrows():
    print(i, j)
    print()

0 name      Ameena
degree       MBA
score         90
Name: 0, dtype: object

1 name      Muskan
degree       BCA
score         40
Name: 1, dtype: object

2 name      Needha
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Sanvi
degree      MBA
score        98
Name: 3, dtype: object

In [7]:
for key, value in df.items():
    print(key, value)
    print()

name 0    Ameena
1    Muskan
2    Needha
3     Sanvi
Name: name, dtype: object

degree 0       MBA
1       BCA
2    M.Tech
3       MBA
Name: degree, dtype: object

score 0    90
1    40
2    80
3    98
Name: score, dtype: int64

In [8]:
for i in df.itertuples():
    print(i)

Pandas(Index=0, name='Ameena', degree='MBA', score=90)
Pandas(Index=1, name='Muskan', degree='BCA', score=40)
Pandas(Index=2, name='Needha', degree='M.Tech', score=80)
Pandas(Index=3, name='Sanvi', degree='MBA', score=98)

In [9]:
columns = list(df)

for i in columns:
    print(df[i])

0    Ameena
1    Muskan
2    Needha
3     Sanvi
Name: name, dtype: object
0       MBA
1       BCA
2    M.Tech
3       MBA
Name: degree, dtype: object
0    90
1    40
2    80
3    98
Name: score, dtype: int64