[Reference](https://mkleinbort.medium.com/the-new-pandas-groupby-explained-c3c65867e1cd)

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    {'userId': [1,1,2,2],
     'date': ['2020-01-01','2020-01-02','2020-01-01','2020-01-02'], 
     'value': [1,1,2, None]}
)

df.groupby('userId').apply(lambda x: x.ffill())

   userId        date  value
0       1  2020-01-01    1.0
1       1  2020-01-02    1.0
2       2  2020-01-01    2.0
3       2  2020-01-02    2.0

In [3]:
df.groupby('userId', group_keys=False).apply(lambda x: x.ffill())

   userId        date  value
0       1  2020-01-01    1.0
1       1  2020-01-02    1.0
2       2  2020-01-01    2.0
3       2  2020-01-02    2.0

In [4]:
df.groupby('userId', group_keys=True).apply(lambda x: x.ffill())

   userId        date  value
0       1  2020-01-01    1.0
1       1  2020-01-02    1.0
2       2  2020-01-01    2.0
3       2  2020-01-02    2.0

In [5]:
df = pd.DataFrame(
    {'userId': ['Alice','Alice','Bob','Bob'],
     'date': ['2020-01-01','2020-01-02','2020-01-01','2020-01-02'], 
     'value': [1,1,2, None]}
    , index=['row-1', 'row-2','row-3','row-4']
)

In [6]:
df.groupby('userId', group_keys=True).apply(lambda x: x.set_index('date'))

                  userId  value
userId date
Alice  2020-01-01  Alice    1.0
       2020-01-02  Alice    1.0
Bob    2020-01-01    Bob    2.0
       2020-01-02    Bob    NaN