[Reference](https://medium.com/codepint/creating-a-customizable-python-visual-in-power-bi-ba27bfae29a7)

In [1]:
import urllib.request
import json
import pandas as pd

web_res = urllib.request.urlopen("https://raw.githubusercontent.com/fanzeyi/pokemon.json/master/pokedex.json")
json_res = json.loads(web_res.read().decode('utf-8'))

pokedex = [ [el['id']
            , el['name']['english']
            , el['type']
            , el['base']['HP']
            , el['base']['Attack']
            , el['base']['Defense']
            , el['base']['Sp. Attack']
            , el['base']['Sp. Defense']
            , el['base']['Speed'] ] for el in json_res]
pokedex_df = pd.DataFrame(pokedex, columns=['id', 'name', 'type', 'HP', 'Attack', 'Defense', 'Sp. Attack', 'Sp. Defense', 'Speed'])

pokedex_main = pokedex_df.drop(columns=['type'])
pokedex_type = pokedex_df[['id', 'type']].explode('type')

In [2]:
web_res = urllib.request.urlopen("https://raw.githubusercontent.com/fanzeyi/pokemon.json/master/pokedex.json")
json_res = json.loads(web_res.read().decode('utf-8'))

In [3]:
pokedex = [ [el['id']
            , el['name']['english']
            , el['type']
            , el['base']['HP']
            , el['base']['Attack']
            , el['base']['Defense']
            , el['base']['Sp. Attack']
            , el['base']['Sp. Defense']
            , el['base']['Speed'] ] for el in json_res]
pokedex_df = pd.DataFrame(pokedex, columns=['id', 'name', 'type', 'HP', 'Attack', 'Defense', 'Sp. Attack', 'Sp. Defense', 'Speed'])

pokedex_main = pokedex_df.drop(columns=['type'])
pokedex_type = pokedex_df[['id', 'type']].explode('type')

In [5]:
pokedex_df

,id,name,type,HP,Attack,Defense,Sp. Attack,Sp. Defense,Speed
0,1,Bulbasaur,"[Grass, Poison]",45,49,49,65,65,45
1,2,Ivysaur,"[Grass, Poison]",60,62,63,80,80,60
2,3,Venusaur,"[Grass, Poison]",80,82,83,100,100,80
3,4,Charmander,[Fire],39,52,43,60,50,65
4,5,Charmeleon,[Fire],58,64,58,80,65,80
...,...,...,...,...,...,...,...,...,...
804,805,Stakataka,"[Rock, Steel]",61,131,211,53,101,13
805,806,Blacephalon,"[Fire, Ghost]",53,127,53,151,79,107
806,807,Zeraora,[Electric],88,112,75,102,80,143
807,808,Meltan,[Steel],46,65,65,55,35,34
808,809,Melmetal,[Steel],135,143,143,80,65,34

In [6]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style="ticks", palette="pastel")

if pokedex_df.iloc[0,0] == 'Boxplot':
    sns.boxplot(x="type", y="Attack", palette=["m", "g"],
                data=pokedex_df)
    sns.despine(offset=10, trim=True)
elif pokedex_df.iloc[0,0] == 'Scatterplot':
    sns.scatterplot(x="type", y="Attack",
                sizes=(1, 8), linewidth=0,
                data=pokedex_df)
elif pokedex_df.iloc[0,0] == 'Violinplot':
    sns.violinplot(data=pokedex_df, x="type", y="Attack", palette="Set3", bw=.2, cut=1, linewidth=1)
plt.show()