[Reference](https://towardsdatascience.com/matching-country-information-in-python-7e1928583644)

In [ ]:
import pycountry

In [ ]:
pycountry.countries.get(alpha_2='KR')

Country(alpha_2='KR', alpha_3='KOR', name='Korea, Republic of', numeric='410')

In [ ]:
pycountry.countries.get(alpha_3='KOR').name

'Korea, Republic of'

In [ ]:
pycountry.countries.search_fuzzy('France')

[Country(alpha_2='FR', alpha_3='FRA', name='France', numeric='250', official_name='French Republic')]

In [ ]:
import pycountry
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-18-2020.csv')

In [ ]:
df.head()

   FIPS Admin2 Province_State  ... Combined_Key Incident_Rate  Case_Fatality_Ratio
0   NaN    NaN            NaN  ...  Afghanistan    127.467544             4.091010
1   NaN    NaN            NaN  ...      Albania   1807.074849             2.049842
2   NaN    NaN            NaN  ...      Algeria    215.208108             2.804887
3   NaN    NaN            NaN  ...      Andorra   9731.443733             1.063971
4   NaN    NaN            NaN  ...       Angola     50.392092             2.318561

[5 rows x 14 columns]

In [44]:
df = pd.read_csv('https://raw.githubusercontent.com/Branden-Kang/Python-practice/master/Data/fifa_data.csv')
df.head()

   Unnamed: 0      ID  ... GKReflexes  Release Clause
0           0  158023  ...        8.0         €226.5M
1           1   20801  ...       11.0         €127.1M
2           2  190871  ...       11.0         €228.1M
3           3  193080  ...       94.0         €138.6M
4           4  192985  ...       13.0         €196.4M

[5 rows x 89 columns]

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/Branden-Kang/Python-practice/master/Data/fifa_data.csv')

def get_official_name(country_name):
    try:
        return pycountry.countries.get(name=country_name).official_name
    except:
        return ("No country name")

df['official_name'] = df.apply(lambda df: get_official_name(df['Nationality']), axis=1)

In [50]:
df.head()

   Unnamed: 0      ID  ... Release Clause                  official_name
0           0  158023  ...        €226.5M             Argentine Republic
1           1   20801  ...        €127.1M            Portuguese Republic
2           2  190871  ...        €228.1M  Federative Republic of Brazil
3           3  193080  ...        €138.6M               Kingdom of Spain
4           4  192985  ...        €196.4M             Kingdom of Belgium

[5 rows x 90 columns]

In [ ]:
import pycountry
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-18-2020.csv')

def findCountryAlpha2(country_name):
    try:
        return pycountry.countries.get(name=country_name).alpha_2
    except:
        return ("not founded!")

def findCountryAlpha3 (country_name):
    try:
        return pycountry.countries.get(name=country_name).alpha_3
    except:
        return ("not founded!")

def findCountryNumeric (country_name):
    try:
        return pycountry.countries.get(name=country_name).numeric
    except:
        return ("not founded!")
    
def findCountryOfficialName (country_name):
    try:
        return pycountry.countries.get(name=country_name).official_name
    except:
        return ("not founded!")
    
df['country_alpha_2'] = df.apply(lambda row: findCountryAlpha2(row.Country_Region) , axis = 1)
df['country_alpha_3'] = df.apply(lambda row: findCountryAlpha3(row.Country_Region) , axis = 1)
df['country_numeric'] = df.apply(lambda row: findCountryNumeric(row.Country_Region) , axis = 1)
df['official_name'] = df.apply(lambda row: findCountryOfficialName(row.Country_Region) , axis = 1)

In [ ]:
df.head()

   FIPS Admin2  ... country_numeric                            official_name
0   NaN    NaN  ...             004          Islamic Republic of Afghanistan
1   NaN    NaN  ...             008                      Republic of Albania
2   NaN    NaN  ...             012  People's Democratic Republic of Algeria
3   NaN    NaN  ...             020                  Principality of Andorra
4   NaN    NaN  ...             024                       Republic of Angola

[5 rows x 18 columns]