[Reference](https://medium.com/analytics-vidhya/basic-dataframe-manipulation-using-pandas-221e12db08b6)

In [1]:
import pandas as pd

team1 = pd.DataFrame({"PLAYER": ["Magic Johnson", "Michael Jordan", 
                                 "Lebron James", "Kevin Durant", 
                                 "Shaquille O’Neal", "James Harden"], 
                      'PPG':[19.50, 30.14, 27.10, 27.00, 23.70, 25.20]})

team1 # calling the dataframe just created

             PLAYER    PPG
0     Magic Johnson  19.50
1    Michael Jordan  30.14
2      Lebron James  27.10
3      Kevin Durant  27.00
4  Shaquille O’Neal  23.70
5      James Harden  25.20

In [2]:
# Second Dataframe creation
team2 = pd.DataFrame({"PLAYER": ["Isiah Thomas", "Kobe Bryant", "Tracy McGrady", "Tim Duncan", "Hakeem Olajuwon", "Karl Malone"], "PPG": [19.20, 25.0, 19.60, 19.00, 21.80, 25.00]})
team2

            PLAYER   PPG
0     Isiah Thomas  19.2
1      Kobe Bryant  25.0
2    Tracy McGrady  19.6
3       Tim Duncan  19.0
4  Hakeem Olajuwon  21.8
5      Karl Malone  25.0

In [3]:
# Third Dataframe creation
team1_stats = pd.DataFrame({"PLAYER": ["Magic Johnson", "Michael Jordan", "Lebron James", "Kevin Durant", "Shaquille O’Neal", "James Harden"], "RPG": [7.20, 6.20,7.40,7.10, 10.90, 5.30]})
team1_stats

             PLAYER   RPG
0     Magic Johnson   7.2
1    Michael Jordan   6.2
2      Lebron James   7.4
3      Kevin Durant   7.1
4  Shaquille O’Neal  10.9
5      James Harden   5.3

In [4]:
# Forth Dataframe creation
team2_stats = pd.DataFrame({"PLAYEER": ["Isiah Thomas", "Kobe Bryant", "Tracy McGrady", "Tim Duncan", "Hakeem Olajuwon", "Karl Malone"], "RPG":[3.60, 5.20, 5.60, 10.80,11.10, 10.10]})
team2_stats

           PLAYEER   RPG
0     Isiah Thomas   3.6
1      Kobe Bryant   5.2
2    Tracy McGrady   5.6
3       Tim Duncan  10.8
4  Hakeem Olajuwon  11.1
5      Karl Malone  10.1

In [5]:
team1.loc[::-1].reset_index(drop=True).head(6) # Reseting the index

team1.loc[:, ::-1].head() # reserving the columns

     PPG            PLAYER
0  19.50     Magic Johnson
1  30.14    Michael Jordan
2  27.10      Lebron James
3  27.00      Kevin Durant
4  23.70  Shaquille O’Neal

# Renaming Column(s)

In [6]:
team2_stats = team2_stats.rename({"PLAYEER":"PLAYER"}, axis='columns')
team2_stats

            PLAYER   RPG
0     Isiah Thomas   3.6
1      Kobe Bryant   5.2
2    Tracy McGrady   5.6
3       Tim Duncan  10.8
4  Hakeem Olajuwon  11.1
5      Karl Malone  10.1

# Reversing All Rows

In [7]:
team1 # Quick display of the dataframe to be able to compare it with the results

             PLAYER    PPG
0     Magic Johnson  19.50
1    Michael Jordan  30.14
2      Lebron James  27.10
3      Kevin Durant  27.00
4  Shaquille O’Neal  23.70
5      James Harden  25.20

In [8]:
team1.loc[::-1].head(6)

             PLAYER    PPG
5      James Harden  25.20
4  Shaquille O’Neal  23.70
3      Kevin Durant  27.00
2      Lebron James  27.10
1    Michael Jordan  30.14
0     Magic Johnson  19.50

In [9]:
team1.loc[::-1].reset_index(drop=True).head(6)

             PLAYER    PPG
0      James Harden  25.20
1  Shaquille O’Neal  23.70
2      Kevin Durant  27.00
3      Lebron James  27.10
4    Michael Jordan  30.14
5     Magic Johnson  19.50

# Reverse All Columns

In [10]:
team1.loc[:, ::-1].head()

     PPG            PLAYER
0  19.50     Magic Johnson
1  30.14    Michael Jordan
2  27.10      Lebron James
3  27.00      Kevin Durant
4  23.70  Shaquille O’Neal

# Merging Dataframes

In [11]:
TEAM_1 = pd.merge(team1, team1_stats, on='PLAYER')
TEAM_1.head(2) # The 2 is to display only the first 2 rows

           PLAYER    PPG  RPG
0   Magic Johnson  19.50  7.2
1  Michael Jordan  30.14  6.2

In [12]:
TEAM_2 = pd.merge(team2, team2_stats, on='PLAYER')
TEAM_2.head(2)

         PLAYER   PPG  RPG
0  Isiah Thomas  19.2  3.6
1   Kobe Bryant  25.0  5.2

# Appending Dataframes

In [13]:
TEAM = TEAM_1.append(TEAM_2, ignore_index=True)
TEAM.shape

(12, 3)

In [14]:
TEAM.head(12)

              PLAYER    PPG   RPG
0      Magic Johnson  19.50   7.2
1     Michael Jordan  30.14   6.2
2       Lebron James  27.10   7.4
3       Kevin Durant  27.00   7.1
4   Shaquille O’Neal  23.70  10.9
5       James Harden  25.20   5.3
6       Isiah Thomas  19.20   3.6
7        Kobe Bryant  25.00   5.2
8      Tracy McGrady  19.60   5.6
9         Tim Duncan  19.00  10.8
10   Hakeem Olajuwon  21.80  11.1
11       Karl Malone  25.00  10.1

# Highlighting Min and Max Column Values

In [15]:
format_dict = {'PPG':'{:.2f}'}

In [16]:
TEAM.style.format(format_dict)

In [17]:
(TEAM.style.format(format_dict)
.highlight_min('PPG', color='red')
.highlight_max('PPG', color='lightgreen'))

## Adding a Column from a List

In [18]:
POS = ['PG', 'SG', 'SF', 'SF', 'C', 'SG', 'PG', 'SG', 'SF', 'PF', 'C', 'PF']
ASS = [11.20, 5.30, 7.40, 4.10, 2.50, 6.3, 9.30, 4.70, 4.40, 3.00, 2.50, 3.60]

In [19]:
TEAM['POS'] = POS
TEAM['ASS'] = ASS
TEAM.head()

             PLAYER    PPG   RPG POS   ASS
0     Magic Johnson  19.50   7.2  PG  11.2
1    Michael Jordan  30.14   6.2  SG   5.3
2      Lebron James  27.10   7.4  SF   7.4
3      Kevin Durant  27.00   7.1  SF   4.1
4  Shaquille O’Neal  23.70  10.9   C   2.5

# Re-organizing Columns

In [20]:
TEAM = TEAM[['PLAYER', 'POS', 'PPG', 'ASS', 'RPG']]
TEAM

              PLAYER POS    PPG   ASS   RPG
0      Magic Johnson  PG  19.50  11.2   7.2
1     Michael Jordan  SG  30.14   5.3   6.2
2       Lebron James  SF  27.10   7.4   7.4
3       Kevin Durant  SF  27.00   4.1   7.1
4   Shaquille O’Neal   C  23.70   2.5  10.9
5       James Harden  SG  25.20   6.3   5.3
6       Isiah Thomas  PG  19.20   9.3   3.6
7        Kobe Bryant  SG  25.00   4.7   5.2
8      Tracy McGrady  SF  19.60   4.4   5.6
9         Tim Duncan  PF  19.00   3.0  10.8
10   Hakeem Olajuwon   C  21.80   2.5  11.1
11       Karl Malone  PF  25.00   3.6  10.1

# Sorting Dataframes by Column Values

In [21]:
TEAM = TEAM.sort_values(by=['PPG'], ascending=False) 
# If you want ascending simply change False to True
TEAM

              PLAYER POS    PPG   ASS   RPG
1     Michael Jordan  SG  30.14   5.3   6.2
2       Lebron James  SF  27.10   7.4   7.4
3       Kevin Durant  SF  27.00   4.1   7.1
5       James Harden  SG  25.20   6.3   5.3
7        Kobe Bryant  SG  25.00   4.7   5.2
11       Karl Malone  PF  25.00   3.6  10.1
4   Shaquille O’Neal   C  23.70   2.5  10.9
10   Hakeem Olajuwon   C  21.80   2.5  11.1
8      Tracy McGrady  SF  19.60   4.4   5.6
0      Magic Johnson  PG  19.50  11.2   7.2
6       Isiah Thomas  PG  19.20   9.3   3.6
9         Tim Duncan  PF  19.00   3.0  10.8

In [22]:
TEAM = TEAM.loc[::1].reset_index(drop=True)
TEAM

              PLAYER POS    PPG   ASS   RPG
0     Michael Jordan  SG  30.14   5.3   6.2
1       Lebron James  SF  27.10   7.4   7.4
2       Kevin Durant  SF  27.00   4.1   7.1
3       James Harden  SG  25.20   6.3   5.3
4        Kobe Bryant  SG  25.00   4.7   5.2
5        Karl Malone  PF  25.00   3.6  10.1
6   Shaquille O’Neal   C  23.70   2.5  10.9
7    Hakeem Olajuwon   C  21.80   2.5  11.1
8      Tracy McGrady  SF  19.60   4.4   5.6
9      Magic Johnson  PG  19.50  11.2   7.2
10      Isiah Thomas  PG  19.20   9.3   3.6
11        Tim Duncan  PF  19.00   3.0  10.8

In [23]:
(TEAM.style.format(format_dict)
.background_gradient(subset='PPG', cmap='Greens'))

# Column & Row Slicing

In [24]:
TEAM.iloc[:, 1:3].head(3)

  POS    PPG
0  SG  30.14
1  SF  27.10
2  SF  27.00

In [25]:
TEAM.loc[2:5]

         PLAYER POS   PPG  ASS   RPG
2  Kevin Durant  SF  27.0  4.1   7.1
3  James Harden  SG  25.2  6.3   5.3
4   Kobe Bryant  SG  25.0  4.7   5.2
5   Karl Malone  PF  25.0  3.6  10.1

In [26]:
TEAM.iloc[2:6]

         PLAYER POS   PPG  ASS   RPG
2  Kevin Durant  SF  27.0  4.1   7.1
3  James Harden  SG  25.2  6.3   5.3
4   Kobe Bryant  SG  25.0  4.7   5.2
5   Karl Malone  PF  25.0  3.6  10.1

# Adding Row(s)

In [27]:
# First we add the row
TEAM.loc[7] = ['Stephen Curry', 'PG', 23.50, 6.60, 4.50] 
# I put him below thee 7th player to respect the coring average (PPG) sorting

# Then, we shift the index by 1
TEAM.index = TEAM.index + 1 

# We sort the index
TEAM = TEAM.sort_index()

# Display the results for QC purposes
TEAM

              PLAYER POS    PPG   ASS   RPG
1     Michael Jordan  SG  30.14   5.3   6.2
2       Lebron James  SF  27.10   7.4   7.4
3       Kevin Durant  SF  27.00   4.1   7.1
4       James Harden  SG  25.20   6.3   5.3
5        Kobe Bryant  SG  25.00   4.7   5.2
6        Karl Malone  PF  25.00   3.6  10.1
7   Shaquille O’Neal   C  23.70   2.5  10.9
8      Stephen Curry  PG  23.50   6.6   4.5
9      Tracy McGrady  SF  19.60   4.4   5.6
10     Magic Johnson  PG  19.50  11.2   7.2
11      Isiah Thomas  PG  19.20   9.3   3.6
12        Tim Duncan  PF  19.00   3.0  10.8

# Profiling Dataframe(s)

In [28]:
import numpy as np

In [29]:
NaN = np.nan
TEAM["FGP"] = NaN
TEAM

              PLAYER POS    PPG   ASS   RPG  FGP
1     Michael Jordan  SG  30.14   5.3   6.2  NaN
2       Lebron James  SF  27.10   7.4   7.4  NaN
3       Kevin Durant  SF  27.00   4.1   7.1  NaN
4       James Harden  SG  25.20   6.3   5.3  NaN
5        Kobe Bryant  SG  25.00   4.7   5.2  NaN
6        Karl Malone  PF  25.00   3.6  10.1  NaN
7   Shaquille O’Neal   C  23.70   2.5  10.9  NaN
8      Stephen Curry  PG  23.50   6.6   4.5  NaN
9      Tracy McGrady  SF  19.60   4.4   5.6  NaN
10     Magic Johnson  PG  19.50  11.2   7.2  NaN
11      Isiah Thomas  PG  19.20   9.3   3.6  NaN
12        Tim Duncan  PF  19.00   3.0  10.8  NaN

In [30]:
import pandas_profiling

In [31]:
# pandas_profiling.ProfileReport(TEAM)

# Dropping Column(s) & Row(s)

In [32]:
TEAM.isna().sum()

PLAYER     0
POS        0
PPG        0
ASS        0
RPG        0
FGP       12
dtype: int64

In [33]:
TEAM = TEAM.drop('FGP', 1)
TEAM.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.

           PLAYER POS    PPG  ASS  RPG
1  Michael Jordan  SG  30.14  5.3  6.2
2    Lebron James  SF  27.10  7.4  7.4
3    Kevin Durant  SF  27.00  4.1  7.1
4    James Harden  SG  25.20  6.3  5.3
5     Kobe Bryant  SG  25.00  4.7  5.2

# Generating Descriptive Statistics

In [34]:
TEAM.describe()

             PPG        ASS        RPG
count  12.000000  12.000000  12.000000
mean   23.661667   5.700000   6.991667
std     3.647739   2.604541   2.449660
min    19.000000   2.500000   3.600000
25%    19.575000   3.975000   5.275000
50%    24.350000   5.000000   6.650000
75%    25.650000   6.800000   8.075000
max    30.140000  11.200000  10.900000

# Basic Visualizing With Plotly

In [35]:
import plotly.express as px

df = TEAM
fig = px.bar(TEAM, x="PPG", y="PLAYER", orientation='h', color='PPG', title="Top Scorers")
fig.show()

In [36]:
df = TEAM
fig = px.bar(TEAM, x="RPG", y="PLAYER", orientation='h', color='POS', title="Top Rebounders")
fig.show()

In [37]:
df = TEAM
fig = px.bar(TEAM, x="ASS", y="PLAYER", orientation='h', color='POS', title="Assist Leaders")
fig.show()