[Reference](https://medium.com/@anala007/how-to-reshape-your-dataframe-with-pandas-stack-and-unstack-functions-3e2c86edc04a)

In [1]:
import pandas as pd
df = pd.DataFrame({'A': ['a1', 'a2', 'a3'], 

                   'B': ['b1', 'b2', 'b3'], 

                   'C': ['c1', 'c2', 'c3']}) 
df

    A   B   C
0  a1  b1  c1
1  a2  b2  c2
2  a3  b3  c3

In [2]:
df_stacked = df.stack()
df_stacked

0  A    a1
   B    b1
   C    c1
1  A    a2
   B    b2
   C    c2
2  A    a3
   B    b3
   C    c3
dtype: object

In [3]:
df_unstacked = df_stacked.unstack()
df_unstacked

    A   B   C
0  a1  b1  c1
1  a2  b2  c2
2  a3  b3  c3