[Reference](https://pub.towardsai.net/the-truly-hardest-of-pandas-pivot-and-melt-clearly-explained-5627d0cf7dc0)

In [1]:
# Load necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Plotting pretty figures and avoid blurry images
%config InlineBackend.figure_format = 'retina'
# Larger scale for plots in notebooks
sns.set_context('talk')

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Enable multiple cell outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
df = pd.DataFrame({'New York': [25]})
df

   New York
0        25

In [4]:
df.melt()

   variable  value
0  New York     25